# Set the base image
FROM node:16.18.1

WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest 
COPY . .

# Build
RUN npm run build

# Expose port
EXPOSE 3000

# Start
# CMD ["npm", "run", "start"]
CMD ["node", ".output/server/index.mjs"]
