# Set the base image
FROM python:3.9

WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest 
COPY . .

# Expose port 5000
EXPOSE 3003

# Start 
CMD ["python", "app.py"]

